// <auto-generated />
using FoodBooking4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodBooking4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250108091614_foodwebk")]
    partial class foodwebk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodBooking4.Models.CombosandItems", b =>
                {
                    b.Property<int>("Combo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Combo_Id"));

                    b.Property<string>("Combo_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Combo_Price")
                        .HasColumnType("int");

                    b.Property<int>("Floor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Res_Id")
                        .HasColumnType("int");

                    b.HasKey("Combo_Id");

                    b.ToTable("CombosandItems");
                });

            modelBuilder.Entity("FoodBooking4.Models.Floor", b =>
                {
                    b.Property<int>("Floorr_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Floorr_Id"));

                    b.Property<int>("FC_Id")
                        .HasColumnType("int");

                    b.Property<string>("Floor_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Floorr_Id");

                    b.ToTable("floors");
                });

            modelBuilder.Entity("FoodBooking4.Models.FoodCourt", b =>
                {
                    b.Property<int>("FC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FC_Id"));

                    b.Property<string>("FC_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FC_Id");

                    b.ToTable("foodCourt");
                });

            modelBuilder.Entity("FoodBooking4.Models.ListOfComboItems", b =>
                {
                    b.Property<int>("Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Item_Id"));

                    b.Property<int>("Combo_Id")
                        .HasColumnType("int");

                    b.Property<string>("Item_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Item_Price")
                        .HasColumnType("int");

                    b.HasKey("Item_Id");

                    b.ToTable("listOfComboItems");
                });

            modelBuilder.Entity("FoodBooking4.Models.RegisterAdmin", b =>
                {
                    b.Property<int>("Admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Emp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Admin_Id");

                    b.ToTable("registerAdmins");
                });

            modelBuilder.Entity("FoodBooking4.Models.RegisterUser", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("registerUsers");
                });

            modelBuilder.Entity("FoodBooking4.Models.Restaurant", b =>
                {
                    b.Property<int>("Res_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Res_Id"));

                    b.Property<int>("Floor_Id")
                        .HasColumnType("int");

                    b.Property<string>("Res_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Res_Id");

                    b.ToTable("restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
